#!/bin/bash

# Automatically run the libMicro benchmark in three different ways:
#   1. Without pinning it to NUMA Node 1
#   2. With pinning it to NUMA Node 1
#   3. With pinning it to NUMA Node 1 && using SCHED_FIFO Priority 1
#
# It automatically appends a "run" number to the results and timings files
# so that you can run it multiple times without worry of overwriting previous
# results.
#
# Note that you should use multiview to construct the HTML reports separately.

if [ -z "$1" ]; then
    echo "Please provide the version of RHEL (e.g. 'rhel6.3')"
    exit 1
fi
HN=`hostname -s`
DN=`dirname $0`
VER=`$DN/bin/tattle -V`

results="$DN/../results"
if [ ! -d "$results" ]; then
    echo "Could not find results dir: $results"
    exit 1
fi

if [ -z "$2" ]; then
	suite="full"
else
	suite=$2
fi

template_base="$results/$1-$HN-$suite"
template_nonuma="$template_base-nonuma-lm.$VER"
template_numa="$template_base-numa.N1m1-lm.$VER"
template_nonuma_chrt="$template_base-nonuma-chrt.f1-lm.$VER"
template_numa_chrt="$template_base-numa.N1m1-chrt.f1-lm.$VER"

function checkit {
    if [ -e "$1" ]; then
        return 1;
    else
        return 0;
    fi
}

function checkem {
    checkit $template_nonuma-run.$1-results.txt || return 1;
    checkit $template_nonuma-run.$1-timings.txt || return 1;
    checkit $template_numa-run.$1-results.txt || return 1;
    checkit $template_numa-run.$1-timings.txt || return 1;
    checkit $template_nonuma_chrt-run.$1-results.txt || return 1;
    checkit $template_nonuma_chrt-run.$1-timings.txt || return 1;
    checkit $template_numa_chrt-run.$1-results.txt || return 1;
    checkit $template_numa_chrt-run.$1-timings.txt || return 1;
    return 0;
}

for (( i = 0; ; i++ )); do
    printf -v idx "%04d" $i
    checkem $idx && break;
done
run="run.$idx"

nodes=$(numactl --hardware | grep available | awk '{print $2}')

echo "!Runit-command: $DN/bench -s $suite" >                             $template_nonuma-$run-results.txt
                      $DN/bench -s $suite >>                             $template_nonuma-$run-results.txt    2> $template_nonuma-$run-timings.txt
if [ "$nodes" == "1" ]; then
    echo "!Runit-command: numactl chrt -f 1 $DN/bench -s $suite" > $template_nonuma_chrt-$run-results.txt
                          numactl chrt -f 1 $DN/bench -s $suite >> $template_nonuma_chrt-$run-results.txt 2> $template_nonuma_chrt-$run-timings.txt
else
    echo "!Runit-command: numactl -N 1 -m 1 $DN/bench -s $suite" >           $template_numa-$run-results.txt
                          numactl -N 1 -m 1 $DN/bench -s $suite >>           $template_numa-$run-results.txt      2> $template_numa-$run-timings.txt
    echo "!Runit-command: numactl -N 1 -m 1 chrt -f 1 $DN/bench -s $suite" > $template_numa_chrt-$run-results.txt
                          numactl -N 1 -m 1 chrt -f 1 $DN/bench -s $suite >> $template_numa_chrt-$run-results.txt 2> $template_numa_chrt-$run-timings.txt
fi
