#!/bin/bash

#
# Copyright 2012 Red Hat, Inc.
#
# The contents of this file are subject to the terms
# of the Common Development and Distribution License
# (the "License").  You may not use this file except
# in compliance with the License.
#
# See the License for the specific language governing
# permissions and limitations under the License.
#

for i in *.txt
do
    diff -cw gold/$i $i
done